name: HydraSeat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC & CMake
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build build --config Release --parallel

    - name: Run Engine Unit Tests
      run: ctest --test-dir build --build-config Release --output-on-failure
